(source "melpa" "http://melpa.milkbox.net/packages/")
(source gnu)
(source marmalade)
(source org)

(depends-on "auctex")
(depends-on "color-theme-sanityinc-tomorrow")
(depends-on "color-theme-solarized")
(depends-on "cython-mode")
(depends-on "flycheck")
(depends-on "go-mode")
(depends-on "go-play")
(depends-on "hungry-delete")
(depends-on "julia-mode")
(depends-on "magit")
(depends-on "nose")
(depends-on "pallet")
(depends-on "php-mode")
(depends-on "undo-tree")
(depends-on "use-package")